# Generated by Django 4.2.7 on 2026-03-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_about_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='About_us_images'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subjects_images'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Teachers_images'),
        ),
    ]
