# Generated by Django 4.2.7 on 2026-03-12 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_about_us_image_alter_subjects_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
    ]
