# Generated by Django 6.0.3 on 2026-03-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_categories_description_categories_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name': 'учителя', 'verbose_name_plural': 'учителя'},
        ),
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание2'),
        ),
    ]
