# Generated by Django 6.0.3 on 2026-03-29 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_teachers_options_alter_categories_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='description',
        ),
        migrations.AlterModelTable(
            name='teachers',
            table='teachers',
        ),
    ]
