# Generated by Django 6.0.3 on 2026-04-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_categories_description_alter_teachers_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
