# Generated by Django 4.2.7 on 2026-03-10 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_categories_options_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='category',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
