# Generated by Django 6.0.3 on 2026-04-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Вопрос')),
                ('option1', models.TextField(blank=True, null=True, verbose_name='Первый вариант')),
                ('option2', models.TextField(blank=True, null=True, verbose_name='Второй вариант')),
                ('option3', models.TextField(blank=True, null=True, verbose_name='Третий вариант')),
                ('option4', models.TextField(blank=True, null=True, verbose_name='Четвёртый вариант')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Верный ответ')),
            ],
            options={
                'verbose_name': 'Теста',
                'verbose_name_plural': 'Тесты',
                'db_table': 'test',
            },
        ),
    ]
