# Generated by Django 6.0.3 on 2026-06-25 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_testquestion_testchoice_useranswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='testing.testquestion'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.testquestion'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selected_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testing.testchoice'),
        ),
    ]
