# Generated by Django 4.2.7 on 2026-03-11 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List_of_teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'список преподавателей',
                'verbose_name_plural': 'списки преподавателей',
                'db_table': 'List_of_teachers',
            },
        ),
        migrations.CreateModel(
            name='Registed_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'зарегистрированный пользователь',
                'verbose_name_plural': 'зарегистрированные пользователи',
                'db_table': 'registed_users',
            },
        ),
        migrations.CreateModel(
            name='List_of_teachers_for_goups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.list_of_teachers', verbose_name='список преподавателей')),
            ],
            options={
                'verbose_name': 'список преподавателей по группам',
                'verbose_name_plural': 'списки преподавателей по группам',
                'db_table': 'List_of_teachers_for_groups',
            },
        ),
        migrations.AddField(
            model_name='list_of_teachers',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.registed_users', verbose_name='зарегистрированные пользователи'),
        ),
        migrations.CreateModel(
            name='List_of_students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.registed_users', verbose_name='зарегистрированный пользователь')),
            ],
            options={
                'verbose_name': 'список студентов',
                'verbose_name_plural': 'списки студентов',
                'db_table': 'List_of_students',
            },
        ),
    ]
