# Generated by Django 6.0.3 on 2026-07-08 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_contacts_of_students_description_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contacts_of_students',
            table='сontacts_of_students',
        ),
        migrations.AlterModelTable(
            name='contacts_of_teachers',
            table='сontacts_of_teachers',
        ),
    ]
