# Generated by Django 6.0.3 on 2026-04-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='ФИО')),
                ('email', models.CharField(max_length=150, unique=True, verbose_name='Email')),
                ('description', models.CharField(max_length=150, unique=True, verbose_name='Текст собщения')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'db_table': 'feedback',
            },
        ),
    ]
