# Generated by Django 6.0.3 on 2026-07-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='From_customers_qestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Тема')),
                ('description', models.CharField(max_length=150, unique=True, verbose_name='Текст собщения')),
            ],
            options={
                'verbose_name': 'Вопросуч',
                'verbose_name_plural': 'Вопросыуч',
                'db_table': 'questions_custoumers',
            },
        ),
    ]
