# Generated by Django 6.0.3 on 2026-04-12 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Вопрос'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500, verbose_name='Текст вопроса')),
                ('more_text', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Доп. инфо')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.tests', verbose_name='База знаний')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('bal', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.question', verbose_name='Вопрос')),
            ],
        ),
    ]
