# Generated by Django 6.0.3 on 2026-04-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='base_of_knowledge',
            options={'verbose_name': 'база_знаний', 'verbose_name_plural': 'базы_знаний'},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'группы', 'verbose_name_plural': 'группы'},
        ),
        migrations.AlterModelTable(
            name='material_for_students',
            table='material_for_students',
        ),
    ]
