# Generated by Django 6.0.3 on 2026-03-16 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='base_of_knowledge',
            options={'verbose_name': 'база_знаний', 'verbose_name_plural': 'бау_знаний'},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'группа', 'verbose_name_plural': 'группы'},
        ),
    ]
