# Generated by Django 6.0.3 on 2026-04-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_base_of_knowledge_options_alter_groups_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='category',
        ),
    ]
