# Generated by Django 6.0.3 on 2026-07-12 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_teachers_сourses_teachrs_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachers_сourses',
            options={'verbose_name': 'уч.курс', 'verbose_name_plural': 'уч.курсы'},
        ),
        migrations.AlterModelOptions(
            name='teachrs_groups',
            options={'verbose_name': 'уч.группа', 'verbose_name_plural': 'уч.группы'},
        ),
        migrations.AlterModelTable(
            name='teachers_сourses',
            table='tcours',
        ),
        migrations.AlterModelTable(
            name='teachrs_groups',
            table='tgroups',
        ),
    ]
